version: "3.7"

services:
  nginx:
    image: nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
      - source: nginx_default_conf
        target: /etc/nginx/conf.d/default.conf
      - source: portainer_proxy_conf
        target: /etc/nginx/conf.d/portainer.conf
    volumes:
      - type: bind
        source: /opt/devops/web_folder
        target: /usr/share/nginx/html
      - type: bind
        source: /etc/letsencrypt
        target: /certs
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - web_network

  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - web_network
    deploy:
      mode: replicated
      replicas: 1

volumes:
  portainer_data:

configs:
  nginx_conf:
    file: ./nginx_conf/nginx.conf
  nginx_default_conf:
    file: ./nginx_conf/conf_d/default.conf
  portainer_proxy_conf:
    file: ./nginx_conf/conf_d/portainer.conf

networks:
  agent_network:
    driver: overlay
    attachable: true
  web_network:
    driver: overlay
    attachable: true
